# Generated by Django 2.2.5 on 2019-09-06 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufactor', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='component',
            old_name='component_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='part_name',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('meter', models.DecimalField(decimal_places=0, max_digits=10)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myequis.Bicycle')),
            ],
        ),
        migrations.CreateModel(
            name='Mounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismount_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismount_record', to='myequis.Record')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myequis.Equipment')),
                ('mount_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mount_record', to='myequis.Record')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myequis.Part')),
            ],
        ),
    ]
