# Generated by Django 2.2.5 on 2019-09-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0005_auto_20190910_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mounting',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myequis.Material'),
        ),
    ]
