# Generated by Django 2.2.5 on 2019-09-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0006_auto_20190910_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['component', 'name']},
        ),
    ]
