# Generated by Django 2.2.5 on 2019-09-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0007_auto_20190910_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={},
        ),
        migrations.AddField(
            model_name='part',
            name='_long_name',
            field=models.CharField(db_column='long_name', default=models.CharField(max_length=100), max_length=200),
        ),
    ]
