# Generated by Django 2.2.5 on 2019-09-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0008_auto_20190910_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='_long_name',
        ),
    ]
