# Generated by Django 2.2.5 on 2019-09-11 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0009_remove_part__long_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mounting',
            name='dismount_record',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismount_record', to='myequis.Record'),
        ),
    ]
