# Generated by Django 2.2.6 on 2019-11-27 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0016_auto_20190917_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='manufactor',
            new_name='manufacture',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='KM',
            new_name='km',
        ),
    ]
