# Generated by Django 2.2.6 on 2019-11-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0017_auto_20191127_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
