# Generated by Django 2.2.6 on 2019-11-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0018_bicycletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='bicycle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myequis.BicycleType'),
            preserve_default=False,
        ),
    ]
