# Generated by Django 2.2.6 on 2019-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0019_bicycle_bicycle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycletype',
            name='component',
            field=models.ManyToManyField(to='myequis.Component'),
        ),
    ]
