# Generated by Django 2.2.6 on 2019-11-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0020_bicycletype_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='dismount_record',
        ),
        migrations.RemoveField(
            model_name='material',
            name='mount_record',
        ),
        migrations.RemoveField(
            model_name='material',
            name='part',
        ),
        migrations.CreateModel(
            name='Mounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismount_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismount_record', to='myequis.Record')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='myequis.Material')),
                ('mount_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mount_record', to='myequis.Record')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myequis.Part')),
            ],
        ),
    ]
