# Generated by Django 2.2.6 on 2019-11-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0021_auto_20191127_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicycletype',
            name='component',
        ),
        migrations.AddField(
            model_name='component',
            name='bicycle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myequis.BicycleType'),
            preserve_default=False,
        ),
    ]
