# Generated by Django 2.2.6 on 2019-11-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0022_auto_20191127_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='bicycle_type',
            new_name='type',
        ),
    ]
