# Generated by Django 2.2.6 on 2019-11-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0023_auto_20191127_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='bicycle_type',
            new_name='type',
        ),
    ]
