# Generated by Django 2.2.6 on 2019-11-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False 
    dependencies = [
        ('myequis', '0025_auto_20191127_1722'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Species',
            new_name='BicycleType',
        ),
    ]
