# Generated by Django 2.2.6 on 2019-11-27 17:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False 
    dependencies = [
        ('myequis', '0026_auto_20191127_1723'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BicycleType',
            new_name='Species',
        ),
    ]
