# Generated by Django 2.2.6 on 2019-11-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0027_auto_20191127_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicycle',
            old_name='type',
            new_name='species',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='type',
            new_name='species',
        ),
    ]
