# Generated by Django 2.2.6 on 2019-11-29 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0028_auto_20191127_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mounting',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='myequis.Material'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mounting',
            name='mount_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mount_record', to='myequis.Record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mounting',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myequis.Part'),
            preserve_default=False,
        ),
    ]
