# Generated by Django 3.2.3 on 2021-06-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0029_auto_20191129_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='disposedAt',
            field=models.DateField(null=True),
        ),
    ]
