# Generated by Django 3.2.3 on 2021-06-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0030_auto_20210601_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='disposedAt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
