# Generated by Django 3.2.3 on 2021-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0031_alter_material_disposedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
