# Generated by Django 3.2.3 on 2021-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0032_material_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
