# Generated by Django 3.2.3 on 2021-06-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0033_alter_material_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='Weight [g]',
            new_name='weight',
        ),
    ]
