# Generated by Django 3.2.3 on 2021-08-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0034_rename_weight [g]_material_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mounting',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
