# Generated by Django 3.2.3 on 2021-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0035_mounting_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mounting',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
