# Generated by Django 3.2.3 on 2021-09-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0040_alter_material_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
    ]
