# Generated by Django 3.2.3 on 2021-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0041_rename_type_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
