# Generated by Django 3.2.3 on 2021-09-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0043_materialtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialType',
            new_name='Type',
        ),
    ]
