# Generated by Django 3.2.3 on 2021-09-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0044_rename_materialtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
    ]
