# Generated by Django 3.2.3 on 2021-09-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0046_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stored',
            field=models.BooleanField(default=False),
        ),
    ]
