# Generated by Django 2.2.5 on 2019-09-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0003_auto_20190906_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mounting',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
    ]
