# Generated by Django 2.2.5 on 2019-09-13 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myequis', '0014_auto_20190913_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='dismount_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismount_record', to='myequis.Record'),
        ),
        migrations.AddField(
            model_name='material',
            name='mount_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mount_record', to='myequis.Record'),
        ),
        migrations.AddField(
            model_name='material',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myequis.Part'),
        ),
        migrations.DeleteModel(
            name='Mounting',
        ),
    ]
